import { useState } from 'react'
import { Link as RouterLink, useNavigate, useSearchParams } from 'react-router-dom'
import { Alert, Box, Button, Paper, Stack, TextField, Typography } from '@mui/material'
import { generateAIRecommendation } from '../api/aiRecommendation'
import { getErrorMessage } from '../api/client'

export function AIRecommendationGeneratePage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [recommendationId, setRecommendationId] = useState(
    searchParams.get('recommendationId') ?? '',
  )
  const [generatedBy, setGeneratedBy] = useState('planner@agencyos.local')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const submit = async () => {
    setBusy(true)
    setError(null)
    try {
      const created = await generateAIRecommendation({
        recommendationId,
        generatedBy,
      })
      navigate(`/ai-recommendations/${created.id}`)
    } catch (err) {
      setError(getErrorMessage(err, 'Failed to generate AI recommendation.'))
    } finally {
      setBusy(false)
    }
  }

  return (
    <Stack spacing={3} maxWidth={640}>
      <Box>
        <Button component={RouterLink} to="/ai-recommendations" size="small" sx={{ mb: 1 }}>
          ← AI Recommendations
        </Button>
        <Typography variant="h4" gutterBottom>
          Generate AI Recommendation
        </Typography>
        <Typography color="text.secondary">
          Creates an immutable advisory suggestion for an existing Recommendation. Does not replace
          or modify the Recommendation (BR-1601 / BR-1608).
        </Typography>
      </Box>

      {error && <Alert severity="error">{error}</Alert>}

      <Paper sx={{ p: 3 }}>
        <Stack spacing={2}>
          <TextField
            label="Recommendation Id"
            value={recommendationId}
            onChange={(event) => setRecommendationId(event.target.value)}
            required
            fullWidth
          />
          <TextField
            label="Generated By"
            value={generatedBy}
            onChange={(event) => setGeneratedBy(event.target.value)}
            required
            fullWidth
          />
          <Stack direction="row" spacing={1}>
            <Button
              variant="contained"
              disabled={busy || !recommendationId || !generatedBy}
              onClick={() => void submit()}
            >
              Generate
            </Button>
            <Button component={RouterLink} to="/ai-recommendations" disabled={busy}>
              Cancel
            </Button>
          </Stack>
        </Stack>
      </Paper>
    </Stack>
  )
}
