import { useState } from 'react'
import { Link as RouterLink, useNavigate, useSearchParams } from 'react-router-dom'
import { Alert, Box, Button, Paper, Stack, TextField, Typography } from '@mui/material'
import { generateExecutiveSummary } from '../api/executiveSummary'
import { getErrorMessage } from '../api/client'

export function ExecutiveSummaryGeneratePage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [recommendationId, setRecommendationId] = useState(
    searchParams.get('recommendationId') ?? '',
  )
  const [aiRecommendationId, setAIRecommendationId] = useState(
    searchParams.get('aiRecommendationId') ?? '',
  )
  const [explainabilityId, setExplainabilityId] = useState(
    searchParams.get('explainabilityId') ?? '',
  )
  const [generatedBy, setGeneratedBy] = useState('executive@agencyos.local')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const submit = async () => {
    setBusy(true)
    setError(null)
    try {
      const created = await generateExecutiveSummary({
        recommendationId,
        generatedBy,
        aiRecommendationId: aiRecommendationId || undefined,
        explainabilityId: explainabilityId || undefined,
      })
      navigate(`/executive-summaries/${created.id}`)
    } catch (err) {
      setError(getErrorMessage(err, 'Failed to generate executive summary.'))
    } finally {
      setBusy(false)
    }
  }

  return (
    <Stack spacing={3} maxWidth={640}>
      <Box>
        <Button component={RouterLink} to="/executive-summaries" size="small" sx={{ mb: 1 }}>
          ← Executive Summaries
        </Button>
        <Typography variant="h4" gutterBottom>
          Generate Executive Summary
        </Typography>
        <Typography color="text.secondary">
          Creates an immutable executive briefing for a Recommendation. Optional AI Recommendation
          and Explainability ids refine the briefing. Never changes source records (BR-1801 /
          BR-1805).
        </Typography>
      </Box>

      {error && <Alert severity="error">{error}</Alert>}

      <Paper sx={{ p: 3 }}>
        <Stack spacing={2}>
          <TextField
            label="Recommendation Id"
            value={recommendationId}
            onChange={(event) => setRecommendationId(event.target.value)}
            required
            fullWidth
          />
          <TextField
            label="AI Recommendation Id (optional)"
            value={aiRecommendationId}
            onChange={(event) => setAIRecommendationId(event.target.value)}
            fullWidth
          />
          <TextField
            label="Explainability Id (optional)"
            value={explainabilityId}
            onChange={(event) => setExplainabilityId(event.target.value)}
            fullWidth
          />
          <TextField
            label="Generated By"
            value={generatedBy}
            onChange={(event) => setGeneratedBy(event.target.value)}
            required
            fullWidth
          />
          <Stack direction="row" spacing={1}>
            <Button
              variant="contained"
              disabled={busy || !recommendationId || !generatedBy}
              onClick={() => void submit()}
            >
              Generate
            </Button>
            <Button component={RouterLink} to="/executive-summaries" disabled={busy}>
              Cancel
            </Button>
          </Stack>
        </Stack>
      </Paper>
    </Stack>
  )
}
