import { useState } from 'react'
import { Link as RouterLink, useNavigate, useSearchParams } from 'react-router-dom'
import {
  Alert,
  Box,
  Button,
  MenuItem,
  Paper,
  Stack,
  TextField,
  Typography,
} from '@mui/material'
import { generateExplainability } from '../api/explainability'
import { getErrorMessage } from '../api/client'

export function ExplainabilityGeneratePage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [recommendationId, setRecommendationId] = useState(
    searchParams.get('recommendationId') ?? '',
  )
  const [aiRecommendationId, setAIRecommendationId] = useState(
    searchParams.get('aiRecommendationId') ?? '',
  )
  const [explanationType, setExplanationType] = useState(
    searchParams.get('aiRecommendationId') ? 'AIRecommendation' : 'Recommendation',
  )
  const [generatedBy, setGeneratedBy] = useState('planner@agencyos.local')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const submit = async () => {
    setBusy(true)
    setError(null)
    try {
      const created = await generateExplainability({
        recommendationId,
        generatedBy,
        explanationType,
        aiRecommendationId:
          explanationType === 'AIRecommendation' && aiRecommendationId
            ? aiRecommendationId
            : undefined,
      })
      navigate(`/explainability/${created.id}`)
    } catch (err) {
      setError(getErrorMessage(err, 'Failed to generate explanation.'))
    } finally {
      setBusy(false)
    }
  }

  return (
    <Stack spacing={3} maxWidth={640}>
      <Box>
        <Button component={RouterLink} to="/explainability" size="small" sx={{ mb: 1 }}>
          ← Explainability
        </Button>
        <Typography variant="h4" gutterBottom>
          Generate Explanation
        </Typography>
        <Typography color="text.secondary">
          Creates an immutable natural-language explanation for a Recommendation or AI
          Recommendation. Does not modify Decision Engine outputs (BR-1701 / BR-1705).
        </Typography>
      </Box>

      {error && <Alert severity="error">{error}</Alert>}

      <Paper sx={{ p: 3 }}>
        <Stack spacing={2}>
          <TextField
            label="Recommendation Id"
            value={recommendationId}
            onChange={(event) => setRecommendationId(event.target.value)}
            required
            fullWidth
          />
          <TextField
            select
            label="Explanation Type"
            value={explanationType}
            onChange={(event) => setExplanationType(event.target.value)}
            fullWidth
          >
            <MenuItem value="Recommendation">Recommendation</MenuItem>
            <MenuItem value="AIRecommendation">AI Recommendation</MenuItem>
          </TextField>
          {explanationType === 'AIRecommendation' && (
            <TextField
              label="AI Recommendation Id"
              value={aiRecommendationId}
              onChange={(event) => setAIRecommendationId(event.target.value)}
              required
              fullWidth
            />
          )}
          <TextField
            label="Generated By"
            value={generatedBy}
            onChange={(event) => setGeneratedBy(event.target.value)}
            required
            fullWidth
          />
          <Stack direction="row" spacing={1}>
            <Button
              variant="contained"
              disabled={
                busy ||
                !recommendationId ||
                !generatedBy ||
                (explanationType === 'AIRecommendation' && !aiRecommendationId)
              }
              onClick={() => void submit()}
            >
              Generate
            </Button>
            <Button component={RouterLink} to="/explainability" disabled={busy}>
              Cancel
            </Button>
          </Stack>
        </Stack>
      </Paper>
    </Stack>
  )
}
