using AgencyOS.Application.Audit;
using AgencyOS.Application.Interfaces;
using AgencyOS.Application.Services;
using AgencyOS.Application.Validators;
using FluentValidation;
using Microsoft.Extensions.DependencyInjection;

namespace AgencyOS.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddScoped<IMissionService, MissionService>();
        services.AddScoped<ILeadService, LeadService>();
        services.AddScoped<IClientService, ClientService>();
        services.AddScoped<IContactService, ContactService>();
        services.AddScoped<IClientContractService, ClientContractService>();
        services.AddScoped<ITaskService, TaskService>();
        services.AddScoped<IExecutionResourceService, ExecutionResourceService>();
        services.AddScoped<IWorkingCalendarService, WorkingCalendarService>();
        services.AddScoped<IHolidayService, HolidayService>();
        services.AddScoped<IWorkingHoursService, WorkingHoursService>();
        services.AddScoped<IResourceAvailabilityService, ResourceAvailabilityService>();
        services.AddScoped<IAssignmentService, AssignmentService>();
        services.AddScoped<ICapacityCalculatorService, CapacityCalculatorService>();
        services.AddScoped<ICapacityHistoryService, CapacityHistoryService>();
        services.AddScoped<IWorkloadCalculatorService, WorkloadCalculatorService>();
        services.AddScoped<IWorkloadHistoryService, WorkloadHistoryService>();
        services.AddScoped<IPlanningTemplateService, PlanningTemplateService>();
        services.AddScoped<IPortfolioService, PortfolioService>();
        services.AddScoped<IRecommendationWorkflowService, RecommendationWorkflowService>();
        services.AddScoped<IRecommendationService, RecommendationService>();
        services.AddScoped<IRecommendationHistoryService, RecommendationHistoryService>();
        services.AddScoped<IRecommendationComparisonService, RecommendationComparisonService>();
        services.AddScoped<IDecisionService, DecisionService>();
        services.AddScoped<IDecisionTimelineService, DecisionService>();
        services.AddScoped<IAuditContext, NullAuditContext>();
        services.AddScoped<AuditService>();
        services.AddScoped<IAuditService>(provider => provider.GetRequiredService<AuditService>());
        services.AddScoped<IAuditQueryService>(provider => provider.GetRequiredService<AuditService>());
        services.AddScoped<IAIRecommendationGenerationService, AIRecommendationGenerationService>();
        services.AddScoped<IAIRecommendationComparisonService, AIRecommendationComparisonService>();
        services.AddScoped<IAIRecommendationService, AIRecommendationService>();
        services.AddScoped<IExplainabilityGenerationService, ExplainabilityGenerationService>();
        services.AddScoped<IExplainabilityService, ExplainabilityService>();
        services.AddScoped<IExecutiveRecommendationSummaryGenerationService, ExecutiveRecommendationSummaryGenerationService>();
        services.AddScoped<IExecutiveRecommendationSummaryComparisonService, ExecutiveRecommendationSummaryComparisonService>();
        services.AddScoped<IExecutiveRecommendationSummaryService, ExecutiveRecommendationSummaryService>();
        services.AddScoped<IAvailabilityEngineService, AvailabilityEngineService>();
        services.AddScoped<IAllocationConflictDetectionService, AllocationConflictDetectionService>();
        services.AddScoped<IDeliveryStrategyBuilderService, DeliveryStrategyBuilderService>();
        services.AddScoped<IDeliveryStrategyEvaluatorService, DeliveryStrategyEvaluatorService>();
        services.AddScoped<IDeliveryStrategyRankingService, DeliveryStrategyRankingService>();
        services.AddScoped<IDeliveryStrategyExplanationService, DeliveryStrategyExplanationService>();
        services.AddScoped<ICompanyDecisionProfileService, CompanyDecisionProfileService>();
        services.AddScoped<ICompanyService, CompanyService>();
        services.AddScoped<ICompanyContext, CompanyContext>();
        services.AddScoped<ICompanyContextService, CompanyContextService>();
        services.AddScoped<IDashboardTrendService, DashboardTrendService>();
        services.AddScoped<IDashboardHealthCalculationService, DashboardHealthCalculationService>();
        services.AddScoped<IDashboardAggregationService, DashboardAggregationService>();
        services.AddScoped<IEnterpriseDashboardService, EnterpriseDashboardService>();
        services.AddScoped<IPortfolioTrendAnalysisService, PortfolioTrendAnalysisService>();
        services.AddScoped<IPortfolioComparisonService, PortfolioComparisonService>();
        services.AddScoped<IPortfolioHealthAnalyticsService, PortfolioHealthAnalyticsService>();
        services.AddScoped<IPortfolioRiskAnalyticsService, PortfolioRiskAnalyticsService>();
        services.AddScoped<IPortfolioAnalyticsService, PortfolioAnalyticsService>();
        services.AddSingleton<ICrossPortfolioScenarioStore, CrossPortfolioScenarioStore>();
        services.AddScoped<IEnterpriseCapacityService, EnterpriseCapacityService>();
        services.AddScoped<IEnterpriseWorkloadService, EnterpriseWorkloadService>();
        services.AddScoped<ICrossPortfolioConflictDetectionService, CrossPortfolioConflictDetectionService>();
        services.AddScoped<ICrossPortfolioBalancingService, CrossPortfolioBalancingService>();
        services.AddScoped<ICrossPortfolioScenarioComparisonService, CrossPortfolioScenarioComparisonService>();
        services.AddScoped<ICrossPortfolioPlanningService, CrossPortfolioPlanningService>();
        services.AddScoped<IPersonalDashboardAggregationService, PersonalDashboardAggregationService>();
        services.AddScoped<IPersonalTimelineService, PersonalTimelineService>();
        services.AddScoped<IPersonalKpiService, PersonalKpiService>();
        services.AddScoped<IMyWorkDashboardService, MyWorkDashboardService>();
        services.AddScoped<IPlanningOverviewService, PlanningOverviewService>();
        services.AddScoped<IPlanningNavigationService, PlanningNavigationService>();
        services.AddScoped<IPlanningHistoryService, PlanningHistoryService>();
        services.AddScoped<IPlanningWorkspaceService, PlanningWorkspaceService>();
        services.AddScoped<IRecommendationOverviewService, RecommendationOverviewService>();
        services.AddScoped<IRecommendationNavigationService, RecommendationNavigationService>();
        services.AddScoped<IRecommendationSummaryService, RecommendationSummaryService>();
        services.AddScoped<IRecommendationWorkspaceService, RecommendationWorkspaceService>();
        services.AddScoped<IDecisionOverviewService, DecisionOverviewService>();
        services.AddScoped<IDecisionNavigationService, DecisionNavigationService>();
        services.AddScoped<IDecisionSummaryService, DecisionSummaryService>();
        services.AddScoped<IDecisionWorkspaceService, DecisionWorkspaceService>();
        services.AddScoped<IExecutiveNavigationService, ExecutiveNavigationService>();
        services.AddScoped<IExecutiveKpiService, ExecutiveKpiService>();
        services.AddScoped<IExecutiveAggregationService, ExecutiveAggregationService>();
        services.AddScoped<IExecutiveOverviewService, ExecutiveOverviewService>();
        services.AddScoped<IExecutiveWorkspaceService, ExecutiveWorkspaceService>();
        services.AddScoped<INotificationQueryService, NotificationQueryService>();
        services.AddScoped<INotificationService, NotificationService>();
        services.AddScoped<INotificationGenerationService, NotificationGenerationService>();
        services.AddScoped<IPersonalMetricsService, PersonalMetricsService>();
        services.AddScoped<IPersonalTrendService, PersonalTrendService>();
        services.AddScoped<IActivitySummaryService, ActivitySummaryService>();
        services.AddScoped<IPersonalProductivityDashboardService, PersonalProductivityDashboardService>();
        services.AddValidatorsFromAssemblyContaining<CreateMissionRequestValidator>();

        return services;
    }
}
