using AgencyOS.Api.Controllers;
using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace AgencyOS.Api.Swagger;

/// <summary>
/// Adds request and response examples for Delivery Strategy Evaluation and Decision Recommendation endpoints.
/// </summary>
public sealed class DeliveryStrategyOpenApiOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        if (context.MethodInfo.DeclaringType != typeof(DeliveryStrategyController))
        {
            return;
        }

        var actionName = context.MethodInfo.Name;

        switch (actionName)
        {
            case nameof(DeliveryStrategyController.Evaluate):
                operation.Summary ??= "Evaluate delivery strategies";
                operation.Description ??=
                    "Evaluates candidate delivery strategies for a contract and mission in the planning period. Strategies are generated by the Delivery Strategy Builder and measured using certified Capacity, Workload, Availability, and Allocation Conflict results. Evaluation produces objective metrics only; it does not rank, recommend, or modify operational data.";
                SetJsonRequestExample(operation, CreateEvaluateRequestExample());
                SetJsonResponseExample(operation, "200", CreateEvaluateResponseExample());
                break;

            case nameof(DeliveryStrategyController.Rank):
                operation.Summary ??= "Rank delivery strategies";
                operation.Description ??=
                    "Ranks evaluated delivery strategies for a contract and mission using a configurable Company Decision Profile. Ranking normalizes evaluation metrics, applies profile weights, and returns an ordered recommendation list from best to worst. Ranking never modifies evaluation metrics or operational data.";
                SetJsonRequestExample(operation, CreateRankRequestExample());
                SetJsonResponseExample(operation, "200", CreateRankResponseExample());
                break;

            case nameof(DeliveryStrategyController.GetExplanation):
                operation.Summary ??= "Explain a ranked delivery strategy";
                operation.Description ??=
                    "Generates a deterministic structured explanation for a ranked delivery strategy. The explanation references ranking position, final score, decision factors, strengths, weaknesses, risks, resource composition, and capacity impact. Explanation never changes ranking and never modifies operational data.";
                SetJsonResponseExample(operation, "200", CreateExplanationResponseExample());
                break;
        }
    }

    private static void SetJsonRequestExample(OpenApiOperation operation, IOpenApiAny example)
    {
        operation.RequestBody ??= new OpenApiRequestBody();
        operation.RequestBody.Content ??= new Dictionary<string, OpenApiMediaType>();

        if (!operation.RequestBody.Content.TryGetValue("application/json", out var mediaType))
        {
            mediaType = new OpenApiMediaType();
            operation.RequestBody.Content["application/json"] = mediaType;
        }

        mediaType.Example = example;
    }

    private static void SetJsonResponseExample(OpenApiOperation operation, string statusCode, IOpenApiAny example)
    {
        if (!operation.Responses.TryGetValue(statusCode, out var response))
        {
            return;
        }

        response.Content ??= new Dictionary<string, OpenApiMediaType>();

        if (!response.Content.TryGetValue("application/json", out var mediaType))
        {
            mediaType = new OpenApiMediaType();
            response.Content["application/json"] = mediaType;
        }

        mediaType.Example = example;
    }

    private static OpenApiObject CreateEvaluateRequestExample() => new()
    {
        ["contractId"] = new OpenApiString("11111111-1111-4111-8111-111111111111"),
        ["missionId"] = new OpenApiString("22222222-2222-4222-8222-222222222222"),
        ["periodStartDate"] = new OpenApiString("2026-07-01"),
        ["periodEndDate"] = new OpenApiString("2026-07-31")
    };

    private static OpenApiObject CreateEvaluateResponseExample() => new()
    {
        ["contractId"] = new OpenApiString("11111111-1111-4111-8111-111111111111"),
        ["missionId"] = new OpenApiString("22222222-2222-4222-8222-222222222222"),
        ["evaluatedStrategyCount"] = new OpenApiInteger(1),
        ["elapsedMilliseconds"] = new OpenApiInteger(42),
        ["evaluatedStrategies"] = new OpenApiArray
        {
            CreateEvaluatedStrategyExample()
        }
    };

    private static OpenApiObject CreateRankRequestExample() => new()
    {
        ["contractId"] = new OpenApiString("11111111-1111-4111-8111-111111111111"),
        ["missionId"] = new OpenApiString("22222222-2222-4222-8222-222222222222"),
        ["periodStartDate"] = new OpenApiString("2026-07-01"),
        ["periodEndDate"] = new OpenApiString("2026-07-31"),
        ["companyDecisionProfileId"] = new OpenApiString("44444444-4444-4444-8444-444444444444")
    };

    private static OpenApiObject CreateRankResponseExample() => new()
    {
        ["contractId"] = new OpenApiString("11111111-1111-4111-8111-111111111111"),
        ["missionId"] = new OpenApiString("22222222-2222-4222-8222-222222222222"),
        ["companyDecisionProfileId"] = new OpenApiString("44444444-4444-4444-8444-444444444444"),
        ["companyDecisionProfileName"] = new OpenApiString("Balanced Strategy"),
        ["rankedStrategyCount"] = new OpenApiInteger(1),
        ["elapsedMilliseconds"] = new OpenApiInteger(55),
        ["rankedStrategies"] = new OpenApiArray
        {
            new OpenApiObject
            {
                ["rankPosition"] = new OpenApiInteger(1),
                ["finalScore"] = new OpenApiDouble(82.5),
                ["evaluatedStrategy"] = CreateEvaluatedStrategyExample(),
                ["decisionFactors"] = CreateDecisionFactorsExample()
            }
        }
    };

    private static OpenApiObject CreateExplanationResponseExample() => new()
    {
        ["strategyId"] = new OpenApiString("33333333-3333-4333-8333-333333333333"),
        ["contractId"] = new OpenApiString("11111111-1111-4111-8111-111111111111"),
        ["missionId"] = new OpenApiString("22222222-2222-4222-8222-222222222222"),
        ["companyDecisionProfileId"] = new OpenApiString("44444444-4444-4444-8444-444444444444"),
        ["strategySummary"] = new OpenApiObject
        {
            ["strategyId"] = new OpenApiString("33333333-3333-4333-8333-333333333333"),
            ["strategyName"] = new OpenApiString("Internal Human"),
            ["rankPosition"] = new OpenApiInteger(1),
            ["totalRankedStrategies"] = new OpenApiInteger(1),
            ["finalScore"] = new OpenApiDouble(82.5),
            ["companyDecisionProfileName"] = new OpenApiString("Balanced Strategy")
        },
        ["decisionFactors"] = CreateDecisionFactorsExample(),
        ["strengths"] = new OpenApiArray
        {
            new OpenApiObject
            {
                ["category"] = new OpenApiString("DecisionFactor"),
                ["dimension"] = new OpenApiString("EstimatedCost"),
                ["normalizedScore"] = new OpenApiDouble(90),
                ["rawValue"] = new OpenApiDouble(1360),
                ["reasonCode"] = new OpenApiString("STRENGTH_HIGH_DECISION_FACTOR_SCORE")
            }
        },
        ["weaknesses"] = new OpenApiArray(),
        ["risks"] = new OpenApiArray(),
        ["resourceComposition"] = new OpenApiObject
        {
            ["humanUtilizationPercentage"] = new OpenApiDouble(100),
            ["aiUtilizationPercentage"] = new OpenApiDouble(0),
            ["externalResourceUtilizationPercentage"] = new OpenApiDouble(0),
            ["automationUtilizationPercentage"] = new OpenApiDouble(0)
        },
        ["capacityImpact"] = new OpenApiObject
        {
            ["capacityUtilizationPercentage"] = new OpenApiDouble(25),
            ["workloadImpactPercentage"] = new OpenApiDouble(10),
            ["availabilityImpactPercentage"] = new OpenApiDouble(20),
            ["resourceUtilizationPercentage"] = new OpenApiDouble(25)
        },
        ["estimatedCost"] = new OpenApiDouble(1360),
        ["estimatedDurationHours"] = new OpenApiDouble(16),
        ["elapsedMilliseconds"] = new OpenApiInteger(60)
    };

    private static OpenApiObject CreateEvaluatedStrategyExample() => new()
    {
        ["strategy"] = new OpenApiObject
        {
            ["strategyId"] = new OpenApiString("33333333-3333-4333-8333-333333333333"),
            ["contractId"] = new OpenApiString("11111111-1111-4111-8111-111111111111"),
            ["missionId"] = new OpenApiString("22222222-2222-4222-8222-222222222222"),
            ["strategyName"] = new OpenApiString("Internal Human"),
            ["estimatedHours"] = new OpenApiDouble(16),
            ["estimatedCost"] = new OpenApiDouble(1360)
        },
        ["evaluationMetrics"] = new OpenApiObject
        {
            ["estimatedCost"] = new OpenApiDouble(1360),
            ["estimatedDurationHours"] = new OpenApiDouble(16),
            ["capacityUtilizationPercentage"] = new OpenApiDouble(25),
            ["resourceUtilizationPercentage"] = new OpenApiDouble(25),
            ["workloadImpactPercentage"] = new OpenApiDouble(10),
            ["availabilityImpactPercentage"] = new OpenApiDouble(20),
            ["operationalRiskScore"] = new OpenApiDouble(15),
            ["humanUtilizationPercentage"] = new OpenApiDouble(100),
            ["aiUtilizationPercentage"] = new OpenApiDouble(0),
            ["automationUtilizationPercentage"] = new OpenApiDouble(0),
            ["externalResourceUtilizationPercentage"] = new OpenApiDouble(0)
        }
    };

    private static OpenApiObject CreateDecisionFactorsExample() => new()
    {
        ["factors"] = new OpenApiArray
        {
            new OpenApiObject
            {
                ["dimension"] = new OpenApiString("EstimatedCost"),
                ["rawValue"] = new OpenApiDouble(1360),
                ["normalizedScore"] = new OpenApiDouble(90),
                ["weight"] = new OpenApiDouble(0.25),
                ["weightedContribution"] = new OpenApiDouble(22.5)
            },
            new OpenApiObject
            {
                ["dimension"] = new OpenApiString("OperationalRisk"),
                ["rawValue"] = new OpenApiDouble(15),
                ["normalizedScore"] = new OpenApiDouble(85),
                ["weight"] = new OpenApiDouble(0.25),
                ["weightedContribution"] = new OpenApiDouble(21.25)
            }
        }
    };
}
